// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationService.Datas.Context;

#nullable disable

namespace ReservationService.Datas.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReservationService.Datas.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActualActiveReservation")
                        .HasColumnType("int");

                    b.Property<DateTime>("Changement")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoSiege")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoVol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualActiveReservation = 0,
                            Changement = new DateTime(2023, 12, 5, 13, 53, 18, 758, DateTimeKind.Local).AddTicks(7317),
                            NoSiege = "A1",
                            NoVol = "A123B",
                            UtilisateurId = 1
                        });
                });

            modelBuilder.Entity("ReservationService.Datas.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActiveReservation")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveReservation = 0,
                            Email = "Agagag.gougk@Email.com",
                            Nom = "Gagak",
                            Prenom = "gougk",
                            UtilisateurId = 0
                        });
                });

            modelBuilder.Entity("ReservationService.Datas.Entities.Reservation", b =>
                {
                    b.HasOne("ReservationService.Datas.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
